//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUCTOS
    {
        public int codigo_pr { get; set; }
        public string descripcion_pr { get; set; }
        public string marca_pr { get; set; }
        public int codigo_ca { get; set; }
        public int codigo_me { get; set; }
        public decimal stock_actual { get; set; }
        public System.DateTime fecha_crea { get; set; }
        public bool activo { get; set; }
    
        public virtual TB_CATEGORIAS TB_CATEGORIAS { get; set; }
        public virtual TB_MEDIDAS TB_MEDIDAS { get; set; }
    }
}
